[ERROR]: Yosys checks have failed: Encountered check error:
Warning: Wire ZeroToFiveCounter.\AN [7] is used but has no driver.

Encountered check error:
Warning: Wire ZeroToFiveCounter.\AN [6] is used but has no driver.

Encountered check error:
Warning: Wire ZeroToFiveCounter.\AN [5] is used but has no driver.

Encountered check error:
Warning: Wire ZeroToFiveCounter.\AN [4] is used but has no driver.

Encountered check error:
Warning: Wire ZeroToFiveCounter.\AN [3] is used but has no driver.

Encountered check error:
Warning: Wire ZeroToFiveCounter.\AN [2] is used but has no driver.

Encountered check error:
Warning: Wire ZeroToFiveCounter.\AN [1] is used but has no driver.

Encountered check error:
Warning: Wire ZeroToFiveCounter.\AN [0] is used but has no driver.

child process exited abnormally
[ERROR]: See the full report here: designs/project3/runs/RUN_2025.05.20_19.57.24/reports/synthesis/1-synthesis_pre_synth.chk.rpt
[ERROR]: Step 1 (synthesis) failed with error:
-code 1 -level 0 -errorstack {INNER {invokeStk1 throw_error} CALL {check_synth_misc /openlane/designs/project3/runs/RUN_2025.05.20_19.57.24/reports/synthesis/1-synthesis_pre_synth.chk.rpt} CALL {run_synthesis_checkers /openlane/designs/project3/runs/RUN_2025.05.20_19.57.24/logs/synthesis/1-synthesis.log /openlane/designs/project3/runs/RUN_2025.05.20_19.57.24/reports/synthesis/1-synthesis_pre_synth.chk.rpt} CALL run_synthesis CALL {run_non_interactive_mode -design project3}} -errorcode NONE -errorinfo {
    while executing
"throw_error"
    (procedure "check_synth_misc" line 17)
    invoked from within
"check_synth_misc $report"
    (procedure "run_synthesis_checkers" line 5)
    invoked from within
"run_synthesis_checkers $log $pre_synth_report"
    (procedure "run_synthesis" line 19)
    invoked from within
"run_synthesis"} -errorline 1
[ERROR]: Failed to create manufacturability and metric reports:
[ERROR]: Traceback (most recent call last):
  File "/openlane/scripts/generate_reports.py", line 184, in <module>
    cli()
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/generate_reports.py", line 51, in cli
    report = Report(design, tag, design_name, params, run_path).get_report()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 809, in get_report
    *self.extract_all_values(),
     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 359, in extract_all_values
    power_report = Artifact(
                   ^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 62, in __init__
    self.pathname = matches[0]
                    ~~~~~~~^^^
IndexError: list index out of range
[ERROR]: Flow failed.
